name = "Hugo Simple"
license = "MIT"
licenselink = "https://github.com/mofelo/hugo-simple/blob/main/LICENSE"
description = "A Hugo-theme based on Simple.css and Bear Blog"
homepage = "https://github.com/mofelo/hugo-simple"
demosite = "https://mofelo.github.io/hugo-simple"

tags = ["blog", "minimal", "fast", "dark mode"]
features = ["favicon", "no javascript", "rss", "dark mode"]

[author]
name = "mofelo"
homepage = "https://github.com/mofelo"

[original]
author = "Caio Lente"
homepage = "https://lente.dev"
repo = "https://github.com/clente/hugo-bearcub"
